table Dim_Producto
	lineageTag: f3f588a8-144b-43da-9b48-752b499c1684

	column ID_Producto
		dataType: int64
		formatString: 0
		lineageTag: f2b97d23-a8c9-4fc8-9ce5-af8cae485d37
		summarizeBy: none
		sourceColumn: ID_Producto

		annotation SummarizationSetBy = Automatic

	column Nombre_Producto
		dataType: string
		lineageTag: a86b9149-1684-48cd-9516-92631a3add93
		summarizeBy: none
		sourceColumn: Nombre_Producto

		annotation SummarizationSetBy = Automatic

	column Categoría
		dataType: string
		lineageTag: c2c05b47-9694-40bb-a663-dd7266ab8fe6
		summarizeBy: none
		sourceColumn: Categoría

		annotation SummarizationSetBy = Automatic

	column Precio_Unitario
		dataType: double
		lineageTag: 97ae91ab-335c-4cce-9af8-311ddb1adf2d
		summarizeBy: none
		sourceColumn: Precio_Unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cantidad Productos' = DISTINCTCOUNT(Fact_Ventas[ID_Producto])
		dataType: int64
		lineageTag: 5c00f3f3-c035-4597-8da6-19c4a5b7af21

	partition Dim_Producto = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("G:\My Drive\estudios\ecotec\docencia\Modelos de Datos\Modelo Estrella\modelo_estrella_ventas.xlsx"), null, true),
				    Dim_Producto_Sheet = Source{[Item="Dim_Producto",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dim_Producto_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Producto", Int64.Type}, {"Nombre_Producto", type text}, {"Categoría", type text}, {"Precio_Unitario", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

